### ISSUE TITLE
No Samples/ Tests

### ISSUE THREAD

**Issue by AArhin** [pierredavidbelanger/jdbi-spring-boot-starter#1]
Hi,
    Can you please create a working sample app ?
Or do you have Tests that you can share ?
Thanks

**Comment by pierredavidbelanger** [comment]
Good point.

I just created a [sample app](https://github.com/pierredavidbelanger/jdbi-spring-boot-starter-sample-app), you should be able to get started with this.

Thank you for the feedback.
